name = "math"
symbols = {
    { CFunction, "abs",        "math_abs" },
    { CFunction, "acos",       "math_acos" },
    { CFunction, "asin",       "math_asin" },
    { CFunction, "atan",       "math_atan" },
    { CFunction, "ceil",       "math_ceil" },
    { CFunction, "cos",        "math_cos" },
    { CFunction, "deg",        "math_deg" },
    { CFunction, "exp",        "math_exp" },
    { CFunction, "tointeger",  "math_toint" },
    { CFunction, "floor",      "math_floor" },
    { CFunction, "fmod",       "math_fmod" },
    { CFunction, "ult",        "math_ult" },
    { CFunction, "log",        "math_log" },
    { CFunction, "max",        "math_max" },
    { CFunction, "min",        "math_min" },
    { CFunction, "modf",       "math_modf" },
    { CFunction, "rad",        "math_rad" },
    { CFunction, "sin",        "math_sin" },
    { CFunction, "sqrt",       "math_sqrt" },
    { CFunction, "tan",        "math_tan" },
    { CFunction, "type",       "math_type" },
 -- [[ LUA_COMPAT_MATHLIB --
    { CFunction, "atan2",      "math_atan" },
    { CFunction, "cosh",       "math_cosh" },
    { CFunction, "sinh",       "math_sinh" },
    { CFunction, "tanh",       "math_tanh" },
    { CFunction, "pow",        "math_pow" },
    { CFunction, "frexp",      "math_frexp" },
    { CFunction, "ldexp",      "math_ldexp" },
    { CFunction, "log10",      "math_log10" },
 -- LUA_COMPAT_MATHLIB ]] --
    { CFunction, "random",     "math_random" },
    { CFunction, "randomseed", "math_randomseed" },
    { Number,    "pi",         "PI" },
    { Number,    "huge",       "(lua_Number)HUGE_VAL" },
    { Integer,   "maxinteger", "LUA_MAXINTEGER" },
    { Integer,   "mininteger", "LUA_MININTEGER" },
}
